org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true

minecraft_version=1.21.10
minecraft_version_range=[1.21.10]
neo_version=21.10.64
mod_version=1.1.8+neoforge.1.21.10.hotfix2

jei_version=26.3.0.31
cloth_config_version=20.0.149
shoulder_surfing_version=wXKW1cn5
player_animation_project=1283899
player_animation_file=7338028
